// Note: This file is autogenerated by generateAllChannels.js
import About from "./channels/main/About";
import Home from "./channels/main/Home";
import NotFound from "./channels/main/NotFound";

export const AllChannels = {
  About: About,
  Home: Home,
  NotFound: NotFound,
};
