// Note: This file is autogenerated automatically
import NotFound from "./channels/NotFound";
import About from "./channels/main/About";
import Contact from "./channels/main/Contact";
import Overview from "./channels/main/Overview";
import Playground from "./channels/main/Playground";
import Projects from "./channels/main/Projects";

export const AllChannels = {
  NotFound,
  About,
  Contact,
  Overview,
  Playground,
  Projects,
};
