// Note: This file is autogenerated by generateAllPosts.js
import Post_1 from "./posts/2024/Post_1";
import Post_2 from "./posts/2024/Post_2";

export const AllPosts = {
  Post_1: Post_1,
  Post_2: Post_2,
};
