// Note: This file is autogenerated automatically
import Post_1 from "./posts/Test/Post_1";
import Post_10 from "./posts/Test/Post_10";
import Post_11 from "./posts/Test/Post_11";
import Post_12 from "./posts/Test/Post_12";
import Post_13 from "./posts/Test/Post_13";
import Post_2 from "./posts/Test/Post_2";
import Post_3 from "./posts/Test/Post_3";
import Post_4 from "./posts/Test/Post_4";
import Post_5 from "./posts/Test/Post_5";
import Post_6 from "./posts/Test/Post_6";
import Post_7 from "./posts/Test/Post_7";
import Post_8 from "./posts/Test/Post_8";
import Post_9 from "./posts/Test/Post_9";

export const AllPosts = {
  Post_1,
  Post_10,
  Post_11,
  Post_12,
  Post_13,
  Post_2,
  Post_3,
  Post_4,
  Post_5,
  Post_6,
  Post_7,
  Post_8,
  Post_9,
};
