// Note: This file is autogenerated automatically
import Post_1 from "./posts/Test/Post_1";
import Post_2 from "./posts/Test/Post_2";
import Post_3 from "./posts/Test/Post_3";
import Post_4 from "./posts/Test/Post_4";
import Post_5 from "./posts/Test/Post_5";
import Post_6 from "./posts/Test/Post_6";
import Post_7 from "./posts/Test/Post_7";

export const Posts = {
  Post_1,
  Post_2,
  Post_3,
  Post_4,
  Post_5,
  Post_6,
  Post_7,
};
