// Note: This file is autogenerated automatically
import Proj_CharmingChineseCulture from "./projects/Proj_CharmingChineseCulture";
import Proj_QiankaCom from "./projects/Proj_QiankaCom";
import Proj_Teapodo from "./projects/Proj_Teapodo";
import Proj_Tingo from "./projects/Proj_Tingo";

export const Projects = {
  Proj_CharmingChineseCulture,
  Proj_QiankaCom,
  Proj_Teapodo,
  Proj_Tingo,
};